#!/usr/bin/env python3
"""Regenerate THIRD_PARTY_LICENSES.md from cargo metadata and the npm lockfile. Run from the repository root."""
import json, subprocess, sys, collections

def rust():
    md = json.loads(subprocess.check_output(["cargo", "metadata", "--format-version", "1", "--locked"], text=True))
    ws = set(md["workspace_members"])
    out = {}
    for p in md["packages"]:
        if p["id"] in ws:
            continue
        out[f'{p["name"]} {p["version"]}'] = p.get("license") or "see crate"
    return dict(sorted(out.items()))

def npm():
    lock = json.load(open("ui/package-lock.json"))
    out = {}
    for path, info in lock["packages"].items():
        if not path or info.get("dev"):
            continue
        name = path.split("node_modules/")[-1]
        out[f'{name} {info.get("version","")}'] = info.get("license", "see package")
    return dict(sorted(out.items()))

def table(title, rows):
    lines = [f"## {title}", "", "| Package | License |", "|---|---|"]
    lines += [f"| {k} | {v} |" for k, v in rows.items()]
    counts = collections.Counter(rows.values())
    return "\n".join(lines), counts

r, rc = table("Rust (runtime and build dependencies of the workspace)", rust())
n, nc = table("npm (production dependencies of the UI)", npm())
bad = [k for k, v in {**rust(), **npm()}.items() if any(x in v for x in ("GPL", "AGPL", "SSPL")) and "LGPL" not in v and "MIT" not in v and "Apache" not in v]
doc = "# Third-party licenses\n\nGenerated by `scripts/gen_licenses.py`. Development-only tools (compilers, test runners, linters) are not shipped.\n\n" + r + "\n\n" + n + "\n"
open("THIRD_PARTY_LICENSES.md", "w").write(doc)
print("rust:", dict(rc)); print("npm:", dict(nc))
if bad:
    print("COPYLEFT-ONLY PACKAGES:", bad); sys.exit(1)
